# Primeiros passos

Para usar o NumPy no seu código Python, basta adicionar a seguinte linha:

In [2]:
import numpy as np

Utilizamos **np** em vez de **numpy** para simplificar a compreensão do código.
Essa é uma prática comum que auxilia a compreensão do código com mais clareza.

É recomendável usar sempre.

O comando ```__version__``` mostra a versão atual instalada no seu ambiente python.

In [3]:
np.__version__

'1.23.5'

# Criando um array

O array é uma estrutura de dados central da biblioteca NumPy.
O objeto array em NumPy é chamado ndarray (abreviação de N-dimensional array).

Criando um array a partir de uma lista.

In [4]:
lista = [1, 2, 3, 4, 5]
lista

[1, 2, 3, 4, 5]

In [5]:
primeiro_ndarray = np.array(lista)
primeiro_ndarray

array([1, 2, 3, 4, 5])

In [6]:
print(type(lista))
print(type(primeiro_ndarray))

<class 'list'>
<class 'numpy.ndarray'>


Criando um array a partir de uma tupla.

In [7]:
tupla = (1, 2, 3, 4, 5)
tupla

(1, 2, 3, 4, 5)

In [8]:
segundo_ndarray = np.array(tupla)
segundo_ndarray

array([1, 2, 3, 4, 5])

In [9]:
print(type(tupla))
print(type(segundo_ndarray))

<class 'tuple'>
<class 'numpy.ndarray'>


Criando um array a partir de uma função da biblioteca Numpy.

## numpy.zeros

Cria um array de zeros.

Argumentos: `numpy.zeros(shape, dtype=float, order='C', *, like=None)`

In [10]:
# O primeiro número da tupla representa a quantidade de linhas e o segundo número representa a quantidade de colunas
array_zeros = np.zeros((2, 3))
array_zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

## numpy.ones

Cria um array de uns.

Argumentos: `numpy.ones(shape, dtype=None, order='C', *, like=None)`

In [11]:
# Cria um array de uns.
# Argumentos: numpy.ones(shape, dtype=None, order='C', *, like=None)
array_uns = np.ones((2, 3))
array_uns

array([[1., 1., 1.],
       [1., 1., 1.]])

## numpy.full

Cria um array com um valor n especificado.

Argumentos: `numpy.full(shape, fill_value, dtype=None, order='C', *, like=None)`

In [12]:
array_full = np.full((2, 3), 7)
array_full

array([[7, 7, 7],
       [7, 7, 7]])

In [13]:
# Também podemos passar como argumento uma string.
array_full = np.full((1, 2), 'Hello World')
array_full

array([['Hello World', 'Hello World']], dtype='<U11')

In [14]:
# Ou uma lista.
array_full = np.full((2, 3), ['A', 'B', 'C'])
array_full

array([['A', 'B', 'C'],
       ['A', 'B', 'C']], dtype='<U1')

## numpy.arange

Cria um array com valores uniformemente espaçados dentro de um intervalo fornecido.

Argumentos: `numpy.arange([start, ]stop, [step, ]dtype=None, *, like=None)`

In [15]:
# Assim como na função range() do Python, a sequência finaliza no número especificado menos 1 (excluindo o valor fornecido).
array_arange = np.arange(1, 11)
array_arange

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
# Outro exemplo:
array_arange = np.arange(1, 21, 2)
array_arange

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

## numpy.random.random

Cria um array de números aleatórios no intervalo [0.0, 1.0]

Argumentos: `numpy.random.random(size=None)`

In [17]:
# O primeiro número da tupla representa a quantidade de linhas e o segundo número representa a quantidade de colunas
array_random = np.random.random((2, 2))
array_random

array([[0.30216564, 0.23136947],
       [0.54391481, 0.66070258]])

## numpy.random.randint

Cria um array de número inteiros aleatórios dentro do intervalo fornecido.

Argumentos: `numpy.random.randint(low, high=None, size=None, dtype=int)`

In [18]:
array_randint = np.random.randint(1, 11, size=(4, 4))
array_randint

array([[ 7,  4,  8,  6],
       [ 5,  1,  3,  1],
       [ 8, 10,  7,  6],
       [10,  5,  3,  6]])

# Arrays multidimensionais

Arrays multidimensionais em NumPy são estruturas de dados que podem armazenar valores em mais de uma dimensão. Em contraste com listas Python regulares, que são unidimensionais, arrays multidimensionais do NumPy permitem representar dados em forma de tabelas com linhas e colunas ou mesmo em dimensões mais altas, como cubos de dados.

- **Array Unidimensional**
  
  Também conhecido como *vetor* ou *array 1D*. Consiste em uma única linha de elementos.

- **Array Bidimensional**
  
  Também conhecido como *matriz* ou *array 2D*. Consiste em linhas e colunas de elementos.

- **Array Tridimensional**
  
  Também conhecido como *tensor* ou *array 3D*. Consiste em uma coleção de matrizes bidimensionais empilhadas. Pode ser visualizado como um cubo de dados.

  ![Arrays Multidimencionais](https://miro.medium.com/v2/resize:fit:1400/1*X0Dg7QfSYtWhSAu-afi8-g.png)


In [19]:
# Criando um array 1D
array_1d = np.array([1, 2, 3])
array_1d

array([1, 2, 3])

In [20]:
# Criando um array 2D
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
# Criando um array 3D
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
array_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])