In [1]:
import numpy as np

# Forma de um Array

## .shape()

- A forma (shape) de um array é o número de elementos em cada dimensão.
- A propriedade ```shape``` retorna uma tupla representando as dimensões (forma) de um ```ndarray```. Onde o primeiro número representa a quantidade de dimensões, o segundo representa a quantidade de linhas e o terceiro representa a quantidade de colunas do array.

In [2]:
# Exemplo com array 1D.
array_1D = np.zeros((3))
array_1D

array([0., 0., 0.])

In [3]:
array_1D.shape

(3,)

In [4]:
# Exemplo com array 2D.
array_2D = np.zeros((2, 3))
array_2D

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
array_2D.shape

(2, 3)

In [6]:
# Exemplo com array 3D.
array_3D = np.zeros((3, 2, 3))
array_3D

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [7]:
array_3D.shape

(3, 2, 3)

# Manipulando dimensões

## .reshape()

A função ```reshape``` permite alterar a forma a um array sem alterar seus dados. Com isso podemos adicionar ou remover dimensões ou alterar o número de elementos em cada dimensão

**Argumentos:**

`numpy.reshape(a, newshape, order='C').`


In [8]:
# Reshape de um array 1D para um array 2D
array_1D = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
array_2D = array_1D.reshape(4, 3)
array_2D

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [9]:
# Reshape de um array 1D para um array 2D.
array_1D = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
array_3D = array_1D.reshape(2, 2, 3)
array_3D

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [10]:
# Reshape de um array 2D para um array 3D.
array_2D = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]])
array_3D = array_2D.reshape(3, 1, 4)
array_3D

array([[[ 1,  2,  3,  4]],

       [[ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12]]])

O `reshape` permite remodelar um array para qualquer formato desejado, desde que o número total de elementos seja mantido. Ou seja, a multiplicação do número de elementos em cada dimensão deve permanecer constante antes e depois da operação de remodelação.

In [11]:
# Exemplo - O array original possui 9 elementos distribuídos em 3 linha e 3 colunas.
array_original = np.random.randint(1, 10, size=(3, 3))
array_original

array([[8, 7, 4],
       [3, 3, 3],
       [9, 7, 3]])

In [12]:
# Isso significa que o novo formato deve acomodar todos os elementos do array original.
novo_array = array_original.reshape(1, 9)
novo_array

array([[8, 7, 4, 3, 3, 3, 9, 7, 3]])

In [13]:
# Se o novo vetor não tiver o número necessário de elementos, um erro será retornado.
novo_array = array_original.reshape(2,3)

ValueError: cannot reshape array of size 9 into shape (2,3)

## .flatten()

A função `flatten` permite "achatar" um array de qualquer dimensão, o transformando num array unidimensional.

In [14]:
array_original = np.random.randint(20, 31, size=(2, 2, 2))
array_original

array([[[27, 30],
        [26, 23]],

       [[27, 24],
        [25, 24]]])

In [15]:
# Vamos "achatar" o array original com flatten
array_achatado = array_original.flatten()
array_achatado

array([27, 30, 26, 23, 27, 24, 25, 24])

In [16]:
# Também podemos fazer isso usando o reshape, basta passar o argumento "-1"
array_achatado_reshape = array_original.reshape(-1)
array_achatado_reshape

array([27, 30, 26, 23, 27, 24, 25, 24])