In [ ]:
import numpy as np

# Indexação

Em Numpy a indexação de arrays refere-se à forma como você acessa elementos individuais ou subconjuntos de elementos em um array, permitindo acessar e manipular dados de maneira eficiente.

Semelhante ao Python, os índices de um array no NumPy começam a partir de zero.

In [ ]:
# Buscando o primeiro elemento de um array 1D.
array_1D = np.array([1, 2, 3, 4])
array_1D[0]

1

In [ ]:
# Buscando o segundo elemento de um array 1D.
array_1D[1]

2

In [ ]:
# Buscando o quinto elemento de array 2D.
array_2D = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])
array_2D[0, 4]

5

In [ ]:
# No exemplo acima buscamos o quinto elemento da primeira linha, agora vamos buscar o terceiro elemento da segunda linha.
array_2D[1, 2]

8

In [ ]:
# Acessando elementos em um array 3D
array_3D = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
array_3D

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
# Buscando o terceiro elemento da segunda linha do primeiro array
array_3D[0, 1, 2]

6

## Último elemento

Podemos acessar os elementos de um `ndarray` de trás para frente utilizando número negativos.

In [ ]:
# Buscando o último elemento de um array 1D.
array_1D = np.array([1, 2, 3, 4])
array_1D[-1]

4

In [ ]:
# Buscando o penúltimo elemento da última linha de um array 2D.
array_2D = np.array([[10, 11, 12], [13,14,15], [16,17,18], [19,20,21]])
array_2D[-1,-2]

20

# Fatiamento

Com `slicing`, é possível extrair ou acessar uma porção específica de um `ndarray`. Essa operação pode ser realizada em uma ou várias dimensões.

**Pontos importantes a serem considerados:**

- O fatiamento permite a seleção de elementos a partir de um índice inicial até um índice final determinado.
- A fatia é indicada utilizando a seguinte sintaxe: `[início:fim]`.
- Também é possível especificar um passo, como em `[início:fim:passo]`.
- Caso o valor inicial não seja fornecido, é considerado como 0.
- Se o valor final não for fornecido, é considerado o comprimento do array naquela dimensão.
- Quando o passo não é fornecido, o valor padrão é 1.

**Argumentos:**

`numpy.array[início:fim:passo]`

## Array 1D

In [ ]:
# Trabalhando com Array 1D
array_1D = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
array_1D

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Fatiamento de um array 1D - Buscando do segundo até o quinto elemento
array_1D[1:5]

array([2, 3, 4, 5])

In [ ]:
# Fatiamento de um array 1D - Buscando do quarto elemento até o final do array
array_1D[3:]

array([ 4,  5,  6,  7,  8,  9, 10])

## Últimos elementos

Podemos fatiar o `ndarray`de trás para frente utilizando número negativos.

In [ ]:
# Fatiamento de um array 1D - Buscando do antepenúltimo elemento até o final do array
array_1D[-3:]

array([ 8,  9, 10])

In [ ]:
# Fatiamento de um array 1D - Buscando do início até penúltimo elemento do array
array_1D[:-1]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## Passo

É o intervalo entre cada elemento da fatia.

In [ ]:
# Fatiamento de um array 1D - Buscando do início até último, pulando dois elementos
array_1D[::2]

array([1, 3, 5, 7, 9])

## Array 2D

In [ ]:
# Trabalhando com array 2D
array_2D = np.array([[10, 20, 30, 40, 50], [60, 70, 80, 90, 100], [110, 120, 130, 140, 150]])
array_2D

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150]])

In [ ]:
# Fatiamento de um array 2D - Buscando a primeira linha
array_2D[0]

array([10, 20, 30, 40, 50])

In [ ]:
# Fatiamento de um array 2D - Buscando a última coluna
array_2D[:, -1]

array([ 50, 100, 150])

In [ ]:
# Fatiamento de um array 2D - Buscando a última coluna - Exibindo na ordem da coluna
array_2D[:, -1].reshape((3, 1))

array([[ 50],
       [100],
       [150]])

In [ ]:
# Fatiamento de um array 2D - Buscando do segundo até o quinto elemento da segunda linha
array_2D[1, 1:5]

array([ 70,  80,  90, 100])

In [ ]:
# Fatiamento de um array 2D - Buscando os dois primeiros elementos de cada linha
array_2D[:, :2]

array([[ 10,  20],
       [ 60,  70],
       [110, 120]])

In [ ]:
# Fatiamento de um array 2D - Buscando os dois últimos elementos de cada linha
array_2D[:, -2:]

array([[ 40,  50],
       [ 90, 100],
       [140, 150]])

In [ ]:
# Fatiamento de um array 2D - Buscando os elementos do "meio" do array
array_2D[:, 2]

array([ 30,  80, 130])

# Ordenação

A função `sort` é usada para ordenar elementos de um `ndarray` ao longo de um eixo específico (vertical ou diagonal). A ordenação pode ser realizada em ordem crescente ou decrescente, dependendo do argumento fornecido.

**Sobre eixos:**

- **Eixo 0 (Linhas):** Ao informar o eixo 0 a ordenação ocorrerá individualmente a cada linha, no sentido vertical.
- **Eixo 1 (Colunas):** Ao informar o eixo 1 a ordenação ocorrerá individualmente a cada coluna, no sentido horizontal.



**Argumentos:**

`numpy.sort(a, axis=-1, kind=None, order=None)`

In [ ]:
# Exemplo de ordenação crescente num array 1D
array_original = np.array(['banana', 'damasco', 'caju', 'amora'])
np.sort(array_original)

array(['amora', 'banana', 'caju', 'damasco'], dtype='<U7')

In [ ]:
# Exemplo de ordenação num array 2D
array_numerico = np.array([[3, 2, 4], [5, 0, 1]])
np.sort(array_numerico)

array([[2, 3, 4],
       [0, 1, 5]])

In [ ]:
# Exemplo de ordenação num array 2D
array_numerico = np.array([[5, 3, 1], [4, 2, 6], [8, 7, 0]])
array_numerico

array([[5, 3, 1],
       [4, 2, 6],
       [8, 7, 0]])

In [ ]:
# Exemplo de ordenação num array 2D - Ordenando por colunas
array_numerico = np.array([[5, 3, 1], [4, 2, 6], [8, 7, 0]])
np.sort(array_numerico, axis=1)

array([[1, 3, 5],
       [2, 4, 6],
       [0, 7, 8]])

In [ ]:
# Exemplo de ordenação num array 2D - Ordenando por linhas
array_numerico = np.array([[5, 3, 1], [4, 2, 6], [8, 7, 0]])
np.sort(array_numerico, axis=0)

array([[4, 2, 0],
       [5, 3, 1],
       [8, 7, 6]])