In [1]:
import numpy as np

# Fancy Indexing

No NumPy, a indexação sofisticada (fancy indexing) nos permite utilizar uma matriz de índices para acessar vários elementos de um array de uma só vez.

A indexação sofisticada pode realizar operações em arrays mais avançadas e eficientes

In [2]:
# Trabalhando com array 1D.
array_1D = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
array_1D

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [3]:
# Utilizando um array de índices para selecionar elementos específicos.
array_indices = np.array([1, 3, 5])
array_indices

array([1, 3, 5])

In [4]:
# Aplicando fancy indexing.
array_1D[array_indices]

array([20, 40, 60])

## Filtragem condicional com `fancy indexing + mask`

In [5]:
# No array a seguir, considere que a primeira coluna corresponde ao identificador (ID) da pessoa, enquanto a segunda coluna indica a idade.
array_pessoa_id_idade = np.array([[1, 18], [2, 32], [3, 24], [4, 45], [5, 26]])
array_pessoa_id_idade

array([[ 1, 18],
       [ 2, 32],
       [ 3, 24],
       [ 4, 45],
       [ 5, 26]])

## Boolean mask

Utilizando uma matriz de booleanos para selecionar elementos baseados em uma condição

In [6]:
# Filtrando pessoas com mais de 30 anos - retorna um array de verdadeiros e falsos.
mask_condicao = array_pessoa_id_idade[:, 1] > 30
mask_condicao

array([False,  True, False,  True, False])

In [7]:
# Aplicando a máscara ao array, retorna os dados que atendem a condição especificada, no caso, pessoas com mais de 30 anos.
array_pessoa_id_idade[mask_condicao]

array([[ 2, 32],
       [ 4, 45]])

## Manipulando Arrays com `fancy indexing + mask`

In [8]:
# No array a seguir, considere que desejamos multiplicar por 10 todos os valores impares
array_2D = np.arange(1, 31).reshape(6, 5)
array_2D

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [9]:
# Aplicando a máscara ao array
mask_condicao = array_2D % 2 != 0
mask_condicao

array([[ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False]])

In [10]:
# Manipulando array e substituindo os valores
array_2D[mask_condicao] = array_2D[mask_condicao] * 10
array_2D

array([[ 10,   2,  30,   4,  50],
       [  6,  70,   8,  90,  10],
       [110,  12, 130,  14, 150],
       [ 16, 170,  18, 190,  20],
       [210,  22, 230,  24, 250],
       [ 26, 270,  28, 290,  30]])

## Filtragem condicional com `numpy.where`

A função `numpy.where` é utilizada para realizar operações condicionais em arrays, permitindo a aplicação de condições para selecionar elementos específicos ou para criar um novo array com base em condições fornecidas.

**Argumentos:**

`numpy.where(condition, [x, y, ]).`

In [11]:
# Considerando o exemplo anterior, agora vamos filtrar pelas pessoas com menos de 25 anos.
array_pessoa_id_idade

array([[ 1, 18],
       [ 2, 32],
       [ 3, 24],
       [ 4, 45],
       [ 5, 26]])

In [12]:
# Aplicando o np.where - note que o resultado retornado correspondem aos índices das pessoas que satisfazem a condição fornecidada, ou seja, pessoas com menos de 25 anos.
np.where(array_pessoa_id_idade[:, 1] < 25)

(array([0, 2], dtype=int64),)

In [13]:
# Aplicando o np.where ao array, retorna os dados que atendem a condição especificada.
array_pessoa_id_idade[np.where(array_pessoa_id_idade[:, 1] < 25)]

array([[ 1, 18],
       [ 3, 24]])

## Manipulando Arrays com `np.where`

Também podemos utilizar o np.where para manipular o array, buscando e substituindo os valores que atendem a condição fornecida

In [14]:
# No array a seguir, considere que desejamos substituir todos os valores pares por 0
array_2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
array_2D

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [15]:
# Aplicando filtro e substituindo os valores
np.where(array_2D % 2 == 0, 0, array_2D)

array([[ 1,  0,  3],
       [ 0,  5,  0],
       [ 7,  0,  9],
       [ 0, 11,  0]])