In [1]:
import numpy as np

# **Vetorização**

A função `np.vectorize` converte funções Python convencionais em funções vetorizadas, permitindo a aplicação eficiente de uma função a cada elemento de um `ndarray`, eliminando a necessidade de lidar explicitamente com loops. Essa abordagem é especialmente valiosa ao operar em arrays, quando as funções foram originalmente concebidas para operar em valores individuais.

In [2]:
array_original = np.arange(1, 6)
array_original

array([1, 2, 3, 4, 5])

In [3]:
# Exemplo - Vamos criar um novo ndarray a partir do array original, onde cada elemento será elevado ao quadro e multiplicado por 10
def minha_funcao(x):
  return (x**2) * 10

funcao_vetorizada = np.vectorize(minha_funcao)

array_modificado = funcao_vetorizada(array_original)
array_modificado

array([ 10,  40,  90, 160, 250])

In [4]:
# Outro Exemplo - Vamos criar um novo ndarray a partir do array original, onde calculamos o fatorial de cada elemento
def fatorial(x):
  fatorial = 1
  for I in range(2, x + 1):
    fatorial *= I
  return fatorial

funcao_vetorizada = np.vectorize(fatorial)

array_modificado = funcao_vetorizada(array_original)
array_modificado

array([  1,   2,   6,  24, 120])

In [5]:
# Isso também é vetorização
array_modificado = array_original + 10
array_modificado

array([11, 12, 13, 14, 15])

# **Broadcasting**

Broadcasting (transmissão) representa a habilidade de realizar operações aritméticas entre arrays com formas e tamanhos distintos.

O Broadcasting permite que o NumPy execute tais operações mesmo quando as dimensões dos arrays são diferentes.

O Broadcasting segue regras específicas para determinar como as dimensões dos arrays se alinham durante as operações.

As dimensões são consideradas compatíveis quando são iguais ou uma delas é 1. Se as dimensões não forem compatíveis, ocorrerá um erro.

---
Aqui estão algumas regras para Broadcasting em NumPy:

1. Se os arrays têm um número diferente de dimensões, preenche-se à esquerda com dimensões de tamanho 1.
2. Se, após a etapa 1, as dimensões ainda não forem compatíveis, um erro é gerado.
3. As dimensões ao longo de uma dimensão particular são consideradas compatíveis se forem iguais ou uma delas for 1.
4. Se as dimensões não são compatíveis, um erro é gerado.

In [6]:
array_3x3 = np.arange(1, 10).reshape(3, 3)
array_3x3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
# Exemplo - Broadcasting - Soma de Colunas
array_3x1 = np.array([1, 0, -1]).reshape(3, 1)
array_3x1

array([[ 1],
       [ 0],
       [-1]])

In [8]:
# Observe que cada elemento de cada coluna do array_3x3 foi somado ao elemento da posição correspondente do array_3x1
array_soma_colunas = array_3x1 + array_3x3
array_soma_colunas

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [9]:
# Exemplo - Broadcasting - Soma de Linhas
array_1x3 = np.array([1, 0, -1])
array_1x3

array([ 1,  0, -1])

In [10]:
# Observe que cada elemento de cada linha do array_3x3 foi somado ao elemento da posição correspondente do array_1x3
array_soma_linhas = array_1x3 + array_3x3
array_soma_linhas

array([[2, 2, 2],
       [5, 5, 5],
       [8, 8, 8]])

## Outras operações

A mesma lógica é aplicada a outras operações como subtração, multiplicação e divisão.

In [11]:
# Exemplo - Broadcasting - Multiplicação
array_1x3 = np.array([2, 0, 1])
array_1x3

array([2, 0, 1])

In [12]:
array_multiplica_linhas = array_1x3 * array_3x3
array_multiplica_linhas

array([[ 2,  0,  3],
       [ 8,  0,  6],
       [14,  0,  9]])

## Apenas um elemento

O Broadcasting também funciona quando `ndarray` possui um único elemento.
![](https://numpy.org/doc/stable/_images/broadcasting_1.png)

In [13]:
# Exemplo - Broadcasting - Um elemento
array_1x1 = np.array([1])
array_1x1

array([1])

In [14]:
array_subtrai_um_elemento = array_3x3 - array_1x1
array_subtrai_um_elemento

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Dimensões incompatíveis

Quando as dimensões são incompatíveis e as regras não são atendidas não é possível realizar o Broadcasting.

![](https://numpy.org/doc/stable/_images/broadcasting_3.png)

In [15]:
array_2x2 = np.array([[10, 20], [30, 40]])
array_2x2

array([[10, 20],
       [30, 40]])

In [16]:
array_soma_incompativel = array_3x3 + array_2x2
array_soma_incompativel

ValueError: operands could not be broadcast together with shapes (3,3) (2,2) 