In [1]:
import numpy as np

## Concatenação

Usamos a função `numpy.concatenate()` para concatenar, mesclar ou unir uma sequência de dois ou mais arrays em um único `ndarray`. A concatenação refere-se à colocação do conteúdo de dois ou mais arrays em um único array. No NumPy do Python, podemos unir arrays por eixos (vertical ou horizontal).

**Argumentos:**

`numpy.concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")`

In [2]:
# Array 1D
array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])
np.concatenate((array_a, array_b))

array([1, 2, 3, 4, 5, 6])

In [3]:
# Array 2D - Eixo 0 (Linhas) - Concatena na vertical
array_c = np.array([[1, 2], [3, 4]])
array_d = np.array([['A', 'B'], ['C', 'D']])
np.concatenate((array_c, array_d), axis=0)

array([['1', '2'],
       ['3', '4'],
       ['A', 'B'],
       ['C', 'D']], dtype='<U11')

In [4]:
# Array 2D - Eixo 1 (Colunas) - Concatena na horizontal
array_e = np.array([[1, 2], [3, 4]])
array_f = np.array([['A', 'B'], ['C', 'D']])
np.concatenate((array_e, array_f), axis=1)

array([['1', '2', 'A', 'B'],
       ['3', '4', 'C', 'D']], dtype='<U11')

Não é possível concatenar arrays de tamanho diferentes!

In [5]:
# Array 2D - Dimensões incompatíveis!
array_g = np.array([[1, 2], [3, 4]])
array_h = np.array(['A', 'B', 'C'])
np.concatenate((array_g, array_h), axis=1)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

## Manipulando Arrays com `np.delete`

A função numpy.delete() é utilizada para remover um ou mais elementos de um array ao longo de um eixo especificado. A função retorna uma nova array com os elementos removidos, e não modifica o array original.

**Argumentos:**

`numpy.delete(arr, obj, axis=None)`

In [6]:
# Array 1D
array_1D = np.array([1, 2, 3, 4, 5, 12])
array_1D

array([ 1,  2,  3,  4,  5, 12])

In [7]:
# Exemplo - Removendo o último elemento de um array 1D
np.delete(array_1D, -1)

array([1, 2, 3, 4, 5])

In [8]:
# Array 2D
array_2D = np.arange(1, 13).reshape(3, 4)
array_2D

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
# Exemplo - Removendo a terceira linha de um array 2D
np.delete(array_2D, 2, axis=0)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
# Exemplo - Removendo a terceira coluna de um array 2D
np.delete(array_2D, 2, axis=1)

array([[ 1,  2,  4],
       [ 5,  6,  8],
       [ 9, 10, 12]])

In [11]:
# Exemplo - Removendo duas primeiras linhas de um array 2D
np.delete(array_2D, [0, 1], axis=0)

array([[ 9, 10, 11, 12]])

# Métodos de agregação de dados

Em NumPy, métodos de agregação são funções que realizam operações em um conjunto de dados, geralmente ao longo de um eixo específico, resultando em um único valor agregado. Esses métodos são úteis para calcular estatísticas resumidas, como média, soma, mínimo, máximo, desvio padrão, entre outros.

In [12]:
array_exemplo = np.random.randint(1, 21, size=(4, 5))
array_exemplo

array([[14, 18, 18, 14,  9],
       [ 8, 15,  4,  4, 10],
       [20, 20,  7, 20,  3],
       [19,  6,  4, 15,  1]])

## Soma  [`.sum()`]

In [13]:
# Soma total
soma_total = np.sum(array_exemplo)
soma_total

229

In [14]:
# Soma das linhas
soma_linhas = np.sum(array_exemplo, axis=1)
soma_linhas.reshape(4,1)

array([[73],
       [41],
       [70],
       [45]])

In [15]:
# Soma das colunas
soma_colunas = np.sum(array_exemplo, axis=0)
soma_colunas

array([61, 59, 33, 53, 23])

## Média [`.mean()`]

In [16]:
# Média total
media_total = np.mean(array_exemplo)
media_total

11.45

In [17]:
# Média das linhas
media_linhas = np.mean(array_exemplo, axis=1)
media_linhas.reshape(4,1)

array([[14.6],
       [ 8.2],
       [14. ],
       [ 9. ]])

In [18]:
# Média das colunas
média_colunas = np.mean(array_exemplo, axis=0)
média_colunas

array([15.25, 14.75,  8.25, 13.25,  5.75])

## Valor mínimo [`min()`]

In [19]:
# Menor valor do array todo
menor_array = np.min(array_exemplo)
menor_array

1

In [20]:
# Menor valor por linha
menor_linha = np.min(array_exemplo, axis=1)
menor_linha.reshape(4, 1)

array([[9],
       [4],
       [3],
       [1]])

In [21]:
# Menor valor por coluna
menor_coluna = np.min(array_exemplo, axis=0)
menor_coluna

array([8, 6, 4, 4, 1])

## Valor máximo [`max()`]

In [22]:
# Maior valor do array todo
maior_array = np.max(array_exemplo)
maior_array

20

In [23]:
# Maior valor por linha
maior_linha = np.max(array_exemplo, axis=1)
maior_linha.reshape(4, 1)

array([[18],
       [15],
       [20],
       [19]])

In [24]:
# Maior valor por coluna
maior_coluna = np.max(array_exemplo, axis=0)
maior_coluna

array([20, 20, 18, 20, 10])

## Soma cumulativa [`cumsum()`]

In [25]:
# Soma cumulativa total
soma_cumulativa_total = np.cumsum(array_exemplo)
soma_cumulativa_total

array([ 14,  32,  50,  64,  73,  81,  96, 100, 104, 114, 134, 154, 161,
       181, 184, 203, 209, 213, 228, 229])

In [26]:
# Soma cumulativa por linha
soma_cumulativa_linha = np.cumsum(array_exemplo, axis=1)
soma_cumulativa_linha

array([[14, 32, 50, 64, 73],
       [ 8, 23, 27, 31, 41],
       [20, 40, 47, 67, 70],
       [19, 25, 29, 44, 45]])

In [27]:
# Soma cumulativa por coluna
soma_cumulativa_coluna = np.cumsum(array_exemplo, axis=0)
soma_cumulativa_coluna

array([[14, 18, 18, 14,  9],
       [22, 33, 22, 18, 19],
       [42, 53, 29, 38, 22],
       [61, 59, 33, 53, 23]])