In [ ]:
import numpy as np

# Arquivos NumPy


Os dados armazenados em NumPy podem ser salvos em vários formatos, como .npy (NumPy binary), .txt (Texto/CSV), .json (JSON) e .h5 (HDF5). Optar por arquivos .npy oferece vantagens significativas:

- **Eficiência de Armazenamento**: O formato binário utilizado (.npy) é altamente eficiente em termos de armazenamento. Esse aspecto é particularmente útil ao lidar com conjuntos de dados extensos, reduzindo os requisitos de espaço e otimizando a velocidade das operações de leitura e escrita.

- **Preservação de Informações**: Ao salvar um array como .npy, o formato inclui informações cruciais sobre os tipos de dados e a forma do array. Isso assegura que, ao carregá-lo, a estrutura original seja recriada com precisão, evitando perda de informações.

- **Carregamento Rápido**: O processo de carregamento de dados a partir de um arquivo .npy é consideravelmente mais rápido do que em formatos de texto, contribuindo para uma eficiência notável durante a manipulação de dados.

- **Compatibilidade com NumPy**: O formato .npy é específico do NumPy, proporcionando uma compatibilidade sólida com outras ferramentas e bibliotecas baseadas em NumPy. Essa característica facilita a integração e o compartilhamento de dados entre diferentes ambientes e aplicações que utilizam a biblioteca NumPy.

# Salvando

## Formato `.npy`

**Argumentos:**

`numpy.save(file, arr, allow_pickle=True, fix_imports=True)[source]`


In [ ]:
# Criando o array que será salvo
array_exemplo = np.arange(1, 201).reshape(5, 4, 10)
array_exemplo

array([[[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
        [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
        [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
        [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40]],

       [[ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
        [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
        [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
        [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80]],

       [[ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
        [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100],
        [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
        [111, 112, 113, 114, 115, 116, 117, 118, 119, 120]],

       [[121, 122, 123, 124, 125, 126, 127, 128, 129, 130],
        [131, 132, 133, 134, 135, 136, 137, 138, 139, 140],
        [141, 142, 143, 144, 145, 146, 147, 148, 149, 150],
        [151, 152, 153, 154, 155, 156, 157, 158, 159, 160]],

       [[161, 162, 163, 164, 165

In [ ]:
# Salvando o array no formato .npy
np.save('1_array_exemplo.npy', array_exemplo)

In [ ]:
# Também podemos salvar sem especificar o formato '.npy'
np.save('2_array_exemplo_x2', (array_exemplo * 2))

## Outros formatos

**Argumentos:**

`numpy.savetxt(fname, X, fmt='%.18e', delimiter=' ', newline='\n', header='', footer='', comments='# ', encoding=None)`


In [ ]:
# Criando o array que será salvo
array_exemplo_2D = np.arange(1, 101).reshape(10, 10)
array_exemplo_2D

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [ ]:
# Guarde essa informação sobre o tipo de dado deste array ;)
array_exemplo_2D.dtype

dtype('int64')

In [ ]:
# Salvando o array no formato .csv
np.savetxt('3_array_exemplo_2D.csv', array_exemplo_2D, delimiter=',', comments='# Salvando no formato .csv')

In [ ]:
# Diferente da função .save(), com a função .savetxt() é necessário especificar um formato
np.savetxt('4_array_exemplo_2D.txt', array_exemplo_2D, delimiter=',')

### Array 3D

Note que nos exemplos acima usamos um array 2D. Não é possível salvar um array 3D em formatos diferentes de .npy

In [ ]:
np.savetxt('array_exemplo.txt', array_exemplo, delimiter=',')

ValueError: Expected 1D or 2D array, got 3D array instead

In [ ]:
# Mas ainda podemos salvar o array se alterarmos duas dimensões
novo_array = array_exemplo.flatten()
novo_array

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [ ]:
np.savetxt('5_array_exemplo.txt', novo_array, delimiter=',', comments='# A forma original deste array é (5, 4, 10)')

## Carregamento

### Formato `.npy`

**Argumentos:**

`numpy.load(file, mmap_mode=None, allow_pickle=False, fix_imports=True, encoding='ASCII', *, max_header_size=10000)`

In [ ]:
# Carregando um array
np.load('1_array_exemplo.npy')

array([[[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
        [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
        [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
        [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40]],

       [[ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
        [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
        [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
        [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80]],

       [[ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
        [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100],
        [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
        [111, 112, 113, 114, 115, 116, 117, 118, 119, 120]],

       [[121, 122, 123, 124, 125, 126, 127, 128, 129, 130],
        [131, 132, 133, 134, 135, 136, 137, 138, 139, 140],
        [141, 142, 143, 144, 145, 146, 147, 148, 149, 150],
        [151, 152, 153, 154, 155, 156, 157, 158, 159, 160]],

       [[161, 162, 163, 164, 165

In [ ]:
# Podemos atribuir o array salvo no arquivo a um novo array
array_exemplo_x2 = np.load('2_array_exemplo_x2.npy')
array_exemplo_x2

array([[[  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
        [ 22,  24,  26,  28,  30,  32,  34,  36,  38,  40],
        [ 42,  44,  46,  48,  50,  52,  54,  56,  58,  60],
        [ 62,  64,  66,  68,  70,  72,  74,  76,  78,  80]],

       [[ 82,  84,  86,  88,  90,  92,  94,  96,  98, 100],
        [102, 104, 106, 108, 110, 112, 114, 116, 118, 120],
        [122, 124, 126, 128, 130, 132, 134, 136, 138, 140],
        [142, 144, 146, 148, 150, 152, 154, 156, 158, 160]],

       [[162, 164, 166, 168, 170, 172, 174, 176, 178, 180],
        [182, 184, 186, 188, 190, 192, 194, 196, 198, 200],
        [202, 204, 206, 208, 210, 212, 214, 216, 218, 220],
        [222, 224, 226, 228, 230, 232, 234, 236, 238, 240]],

       [[242, 244, 246, 248, 250, 252, 254, 256, 258, 260],
        [262, 264, 266, 268, 270, 272, 274, 276, 278, 280],
        [282, 284, 286, 288, 290, 292, 294, 296, 298, 300],
        [302, 304, 306, 308, 310, 312, 314, 316, 318, 320]],

       [[322, 324, 326, 328, 330

### Outros Formatos

**Argumentos:**

```
numpy.loadtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, converters=None, skiprows=0, usecols=None, unpack=False, ndmin=0, encoding='bytes', max_rows=None, *, quotechar=None, like=None)
```

In [ ]:
# Carregando um array
novo_array_exemplo_2D = np.loadtxt('3_array_exemplo_2D.csv', delimiter=',')
novo_array_exemplo_2D

array([[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.],
       [ 11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.],
       [ 21.,  22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.],
       [ 31.,  32.,  33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.],
       [ 41.,  42.,  43.,  44.,  45.,  46.,  47.,  48.,  49.,  50.],
       [ 51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.,  60.],
       [ 61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.],
       [ 71.,  72.,  73.,  74.,  75.,  76.,  77.,  78.,  79.,  80.],
       [ 81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,  89.,  90.],
       [ 91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99., 100.]])

In [ ]:
# Note que no exemplo acima o dtype do array original armazenado não foi preservado
novo_array_exemplo_2D.dtype

dtype('float64')

In [ ]:
# Outro exemplo
np.loadtxt('4_array_exemplo_2D.txt', delimiter=',')

array([[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.],
       [ 11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.],
       [ 21.,  22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.],
       [ 31.,  32.,  33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.],
       [ 41.,  42.,  43.,  44.,  45.,  46.,  47.,  48.,  49.,  50.],
       [ 51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.,  60.],
       [ 61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.],
       [ 71.,  72.,  73.,  74.,  75.,  76.,  77.,  78.,  79.,  80.],
       [ 81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,  89.,  90.],
       [ 91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99., 100.]])

In [ ]:
# Resgatando e remodelando o array achatado
novo_array_exemplo_3D = np.loadtxt('5_array_exemplo.txt', delimiter=',').reshape(5, 4, 10)
novo_array_exemplo_3D

array([[[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.],
        [ 11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.],
        [ 21.,  22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.],
        [ 31.,  32.,  33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.]],

       [[ 41.,  42.,  43.,  44.,  45.,  46.,  47.,  48.,  49.,  50.],
        [ 51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.,  60.],
        [ 61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.],
        [ 71.,  72.,  73.,  74.,  75.,  76.,  77.,  78.,  79.,  80.]],

       [[ 81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,  89.,  90.],
        [ 91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99., 100.],
        [101., 102., 103., 104., 105., 106., 107., 108., 109., 110.],
        [111., 112., 113., 114., 115., 116., 117., 118., 119., 120.]],

       [[121., 122., 123., 124., 125., 126., 127., 128., 129., 130.],
        [131., 132., 133., 134., 135., 136., 137., 138., 139., 140.],
        [141.,