In [1]:
import numpy as np

# Exercícios para fixação

## 01. Gere um array contendo 4 linhas e 3 colunas, preenchido com valores aleatórios.

In [2]:
array = np.random.random((4, 3))
array

array([[0.52200193, 0.657885  , 0.11724235],
       [0.30482958, 0.31861277, 0.46474339],
       [0.92470029, 0.22465945, 0.48625576],
       [0.69449904, 0.10735375, 0.54509072]])

## 02. Gere um array contendo 3 linhas e 5 colunas, preenchido valores inteiros aleatórios.

In [3]:
array_inteiros = np.random.randint(1, 9, size=(3, 5))
array_inteiros

array([[5, 6, 3, 7, 5],
       [2, 2, 8, 5, 3],
       [6, 5, 1, 2, 4]])

## 03. Gere um array contendo 10 linhas e 5 colunas, preenchido com zeros.

In [4]:
array_zeros = np.zeros((10, 5))
array_zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## 04. Gere um array que inclua valores de 0 a 90, com intervalos de 4 unidades.

In [5]:
array_arange = np.arange(0, 91, 4)
array_arange

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64,
       68, 72, 76, 80, 84, 88])

## 05. Transforme um array de dimensões (5,7) em uma única dimensão.

In [6]:
array_5x7 = np.full((5, 7), 'A')
array_5x7

array([['A', 'A', 'A', 'A', 'A', 'A', 'A'],
       ['A', 'A', 'A', 'A', 'A', 'A', 'A'],
       ['A', 'A', 'A', 'A', 'A', 'A', 'A'],
       ['A', 'A', 'A', 'A', 'A', 'A', 'A'],
       ['A', 'A', 'A', 'A', 'A', 'A', 'A']], dtype='<U1')

In [7]:
array_5x7.flatten()

array(['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A',
       'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A',
       'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A'], dtype='<U1')

## 06. Supondo que você atue como coordenadora de um evento de bingo, é necessário criar um array para representar as cartelas utilizadas no jogo. Os números presentes nas cartelas estão no intervalo de 1 a 30, e há 10 participantes. Cada cartela é composta por 12 números distribuídos em um formato (4, 3). Crie um array que represente este jogo.

In [8]:
cartela_bingo = np.random.randint(1, 31, size=(10, 4, 3))
cartela_bingo

array([[[ 9, 14, 18],
        [30,  4,  1],
        [28,  1, 21],
        [ 2, 18, 13]],

       [[21, 21, 22],
        [15, 17,  3],
        [20,  1, 25],
        [23, 24,  4]],

       [[30,  3, 24],
        [ 6, 22, 11],
        [22, 18, 26],
        [ 6, 23,  6]],

       [[12, 26, 19],
        [29, 20,  9],
        [ 1, 17, 25],
        [ 5, 26, 29]],

       [[19, 11, 28],
        [ 6,  8,  8],
        [ 1, 11,  6],
        [14, 27, 10]],

       [[15, 19, 18],
        [ 9, 26,  9],
        [24, 18, 14],
        [21,  2, 19]],

       [[ 3,  8, 28],
        [18, 16, 24],
        [26,  5,  1],
        [ 9,  4, 28]],

       [[27, 21, 15],
        [13,  1, 15],
        [ 9,  2, 16],
        [20, 19, 13]],

       [[21,  4,  1],
        [19, 22, 30],
        [27, 27, 10],
        [ 9, 14, 25]],

       [[25, 17, 17],
        [12, 11, 18],
        [ 2, 20, 18],
        [20, 27,  8]]])

In [9]:
# Reshape - Transformando em 5 cartelas de 4 linhas e 6 colunas
cartela_bingo.reshape(5, 4, 6)

array([[[ 9, 14, 18, 30,  4,  1],
        [28,  1, 21,  2, 18, 13],
        [21, 21, 22, 15, 17,  3],
        [20,  1, 25, 23, 24,  4]],

       [[30,  3, 24,  6, 22, 11],
        [22, 18, 26,  6, 23,  6],
        [12, 26, 19, 29, 20,  9],
        [ 1, 17, 25,  5, 26, 29]],

       [[19, 11, 28,  6,  8,  8],
        [ 1, 11,  6, 14, 27, 10],
        [15, 19, 18,  9, 26,  9],
        [24, 18, 14, 21,  2, 19]],

       [[ 3,  8, 28, 18, 16, 24],
        [26,  5,  1,  9,  4, 28],
        [27, 21, 15, 13,  1, 15],
        [ 9,  2, 16, 20, 19, 13]],

       [[21,  4,  1, 19, 22, 30],
        [27, 27, 10,  9, 14, 25],
        [25, 17, 17, 12, 11, 18],
        [ 2, 20, 18, 20, 27,  8]]])

## Para os exercícios 7 e 8 considere o array a seguir.


|              | Cliente 01 | Cliente 02 | Cliente 03 |
|:------------:|:----------:|:----------:|:----------:|
| **Ano 01**   |      1     |      3     |      2     |
| **Ano 02**   |      0     |      1     |      0     |
| **Ano 03**   |      2     |      1     |      4     |
| **Ano 04**   |      0     |      0     |      0     |
| **Ano 05**   |      1     |      1     |      0     |

In [10]:
# Os elementos representão a quantidade de acidentes cometidos pelos clientes a cada ano.
array_acidentes = np.array([[1, 3, 2],
                            [0, 1, 0],
                            [2, 1, 4],
                            [0, 0, 0],
                            [1, 1, 0]])
array_acidentes

array([[1, 3, 2],
       [0, 1, 0],
       [2, 1, 4],
       [0, 0, 0],
       [1, 1, 0]])

## 07. Identifique a média de acidentes anual e a média de acidentes por cliente.

In [11]:
# Encontra a média de acidentes por ano
media_acidentes_anual = np.mean(array_acidentes, axis=1)
media_acidentes_anual

array([2.        , 0.33333333, 2.33333333, 0.        , 0.66666667])

In [12]:
# Encontra a média de acidentes por cliente
media_acidentes_cliente = np.mean(array_acidentes, axis=0)
media_acidentes_cliente

array([0.8, 1.2, 1.2])

## 08. Quais clientes passaram pelo menos 2 anos sem cometer acidentes?

In [13]:
clientes_sem_acidentes = np.where(np.sum(array_acidentes == 0, axis=0) >= 2)[0]
clientes_sem_acidentes

array([0, 2], dtype=int64)

## 09. A professora fornece dois arrays aos alunos e solicita a aplicação da função (3x + 2y + x*y) nos elementos destes arrays.

In [14]:
# Suponha que a professora forneceu os seguintes arrays aos alunos
array_x = np.array([1, 2, 3])
array_y = np.array([4, 5, 6])

# Aplica a função (3x + 2y + x*y) nos elementos correspondentes
resultado = 3 * array_x + 2 * array_y + array_x * array_y
resultado

array([15, 26, 39])

## 10. A professora percebeu que esqueceu de registrar as notas dos trabalhos apresentados durante o semestre em todas as provas dos estudantes. Como os trabalhos foram feitos em grupo, ela decidiu adicionar a mesma nota para todos os estudantes. Cada estudante é representado por uma linha no array, e cada coluna corresponde a uma prova. Adicione os valores [1, 2, 1] a cada prova de cada estudante.

In [15]:
notas_provas = np.array([[80, 75, 90],
                         [92, 88, 78],
                         [85, 89, 91]])

# Adiciona os valores [1, 2, 1] a cada prova de cada estudante
notas_provas += np.array([1, 2, 1])
notas_provas

array([[81, 77, 91],
       [93, 90, 79],
       [86, 91, 92]])

## Para os exercícios a seguir considere o cenário apresentado abaixo:

Como bióloga marinha em uma expedição nas profundezas do Oceano Pacífico, estudamos a biodiversidade e a saúde dos recifes de coral.

O catálogo abaixo exibe dados das espécies encontradas.

Considere a seguinte ordem das colunas: **ID da espécie, quantidade de representantes encontrados, profundeza, tamanho médio da espécie**.

ID | Qtde | Profundeza | Tamanho |
---|------|------------|---------|
747|  89  | 33         |  5      |
623| 123  | 32         | 13      |
501|  22  | 49         |  2      |
116| 101  | 42         | 10      |
297|  56  | 69         | 22      |
613|  64  | 27         |  7      |
295|  84  | 29         | 14      |
692| 105  | 72         | 16      |
229| 103  | 35         |  5      |
374| 124  | 70         |  1      |

In [16]:
especies = np.array([[747,  89,  33,   5],
                     [623, 123,  32,  13],
                     [501,  22,  49,   2],
                     [116, 101,  42,  10],
                     [297,  56,  69,  22],
                     [613,  64,  27,   7],
                     [295,  84,  29,  14],
                     [692, 105,  72,  16],
                     [229, 103,  35,   5],
                     [374, 124,  70,   1]])
especies

array([[747,  89,  33,   5],
       [623, 123,  32,  13],
       [501,  22,  49,   2],
       [116, 101,  42,  10],
       [297,  56,  69,  22],
       [613,  64,  27,   7],
       [295,  84,  29,  14],
       [692, 105,  72,  16],
       [229, 103,  35,   5],
       [374, 124,  70,   1]])

## 11. Extraia a segunda coluna, representando a quantidade de espécies encontradas, e adicione-a a um array quantidade_especies.

In [17]:
quantidade_especies = especies[:, 1]
quantidade_especies

array([ 89, 123,  22, 101,  56,  64,  84, 105, 103, 124])

## 12. A partir de quantidade_especies, exiba apenas as três primeiras quantidades.

In [18]:
tres_primeiras_quantidades = quantidade_especies[:3]
tres_primeiras_quantidades

array([ 89, 123,  22])

## 13. Exiba as cinco últimas quantidades de espécies de quantidade_especies.

In [19]:
cinco_ultimas_quantidades = quantidade_especies[-5:]
cinco_ultimas_quantidades

array([ 64,  84, 105, 103, 124])

## 14. Crie um array contendo apenas os tamanhos das espécies e ordene-o em ordem crescente.

In [20]:
tamanhos_especies_ordenados = np.sort(especies[:, 3])
tamanhos_especies_ordenados

array([ 1,  2,  5,  5,  7, 10, 13, 14, 16, 22])

## 15. Utilizando um índice booleano, crie um array contendo os dados da maior espécie encontrada *(Dica: esse valor corresponde a 22)*.

In [21]:
# Encontra o maior valor da coluna Tamanho
maior_valor_colTamaho= np.max(especies[:, 3])

# Cria mask
indice_maior_especie = especies[:, 3] == maior_valor_colTamaho

# Aplica o mask ao array
maior_especie = especies[indice_maior_especie]
maior_especie

array([[297,  56,  69,  22]])

## 16. Através do índice sofisticado (fancy indexing), crie um array incluindo apenas os dados da espécie com ID 297.

In [22]:
# Encontra indice do ID 297
indice_especie_297 = np.where(especies[:, 0] == 297)

# Crie um array incluindo apenas os dados da espécie com ID 297 usando fancy indexing
especie_297_dados = especies[indice_especie_297]
especie_297_dados

array([[297,  56,  69,  22]])

## 17. Utilizando np.where(), crie um array contendo apenas os dados da espécie cuja quantidade de representantes encontrados é 105.

In [23]:
# Encontra indice do ID 297
indice_representantes_105 = np.where(especies[:, 1] == 105)[0]

# Crie um array contendo apenas os dados da espécie com quantidade = 105 usando fancy indexing
especie_representantes_105 = especies[indice_representantes_105]
especie_representantes_105

array([[692, 105,  72,  16]])

## 18. Considere a profundeza em que a espécie foi encontrada e substitua os valores
maiores que 60 por "Profundo".

In [24]:
np.where(especies[:, 2] > 60, "Profundo", especies[:, 2])

array(['33', '32', '49', '42', 'Profundo', '27', '29', 'Profundo', '35',
       'Profundo'], dtype='<U11')

## 19. Adicione duas novas espécies ao array: [204, 10, 40, 12], [392, 11, 81, 11]].

In [25]:
novas_especies = np.array([[204, 10, 40, 12],
                           [392, 11, 81, 11]])
np.concatenate((especies, novas_especies), axis=0)

array([[747,  89,  33,   5],
       [623, 123,  32,  13],
       [501,  22,  49,   2],
       [116, 101,  42,  10],
       [297,  56,  69,  22],
       [613,  64,  27,   7],
       [295,  84,  29,  14],
       [692, 105,  72,  16],
       [229, 103,  35,   5],
       [374, 124,  70,   1],
       [204,  10,  40,  12],
       [392,  11,  81,  11]])

## 20. Acrescente uma nova coluna ao array original indicando a capacidade de enxergar: [0, 1, 0, 0, 0, 0, 1, 0, 1, 1].

In [26]:
capacidade_enxergar = np.array([0, 1, 0, 0, 0, 0, 1, 0, 1, 1]).reshape(10, 1)
capacidade_enxergar

array([[0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1]])

In [27]:
np.concatenate((especies, capacidade_enxergar), axis=1)

array([[747,  89,  33,   5,   0],
       [623, 123,  32,  13,   1],
       [501,  22,  49,   2,   0],
       [116, 101,  42,  10,   0],
       [297,  56,  69,  22,   0],
       [613,  64,  27,   7,   0],
       [295,  84,  29,  14,   1],
       [692, 105,  72,  16,   0],
       [229, 103,  35,   5,   1],
       [374, 124,  70,   1,   1]])